# Исследовательский анализ данных

**Цель работы:**

Изучение связи между признаками двумерного набора данных, визуализация данных.

### Описание предметной области

Вариант №1

Набор данных: датасет drivers.csv содержит информацию о поездках такси.  
Атрибуты:
1. Дата и время начала
2. Дата и время окончания
3. Категория
4. Место начала (можно не проверять данный столбец на наличие
неявных дубликатов)
5. Место окончания (можно не проверять данный столбец на наличие
неявных дубликатов)
6. Пройденные мили
7. Цель поездки
8. Время поездки в минутах
9. Скорость в пути
10. Цена поездки

### 1. Чтение файла и обзор данных

#### 1.2 Знакомство со структурой таблицы с помощью метода head

Исходные табличные данные преобразуются в датафрейм.

In [1]:
import pandas as pd

df = pd.read_csv('drivers2.csv')
df.head()

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*,time,speed,price
0,2016-01-01 21:11:00,2016-01-01 21:17:00,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain,6.0,51.000000,788.0
1,2016-01-02 01:25:00,2016-01-02 01:37:00,Business,Fort Pierce,Fort Pierce,5.0,NaN,12.0,25.000000,1237.0
2,2016-01-02 20:25:00,2016-01-02 20:38:00,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies,13.0,22.153846,1312.0
3,2016-01-05 17:31:00,2016-01-05 17:45:00,Business,Fort Pierce,Fort Pierce,4.7,Meeting,14.0,20.142857,1387.0
4,2016-01-06 14:42:00,2016-01-06 15:49:00,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit,67.0,57.044776,5376.0

Для целостности названия всех полей приводятся к единому виду: латинские строчные буквы, без лишних символов.

In [2]:
df = df.rename(columns={'START_DATE*':'start_date', 'END_DATE*':'end_date', 'CATEGORY*':'category', 'START*':'start_loc', 'STOP*':'stop_loc', 'MILES*':'miles', 'PURPOSE*':'purpose'})

#### 1.2 Оценка данных

Данные, которые хранятся в csv-файлах и используются для анализа, могут содержать ошибки, которые необходимо устранить перед непосредственным анализом. Метод info() предоставляет общую информацию о таблице: её размеры, названия столбцов, типы данных значений, хранящихся в них, а также количество ненулевых значений в каждом столбце.

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1099 entries, 0 to 1098
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   start_date  1099 non-null   str
 1   end_date    1099 non-null   str
 2   category    1099 non-null   str
 3   start_loc   1099 non-null   str
 4   stop_loc    1099 non-null   str
 5   miles       1099 non-null   float64
 6   purpose     598 non-null    str
 7   time        1099 non-null   float64
 8   speed       1099 non-null   float64
 9   price       1099 non-null   float64
dtypes: float64(4), str(6)
memory usage: 162.9 KB

In [4]:
df.describe()

C:\AppDataScience\anaconda3\Lib\site-packages\pandas\core\nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

             miles         time        speed         price
count  1099.000000  1099.000000  1099.000000   1099.000000
mean     10.803094    23.300273          inf   2085.929936
std      22.044580    27.745836          NaN   2084.368402
min       0.500000     0.000000     3.917355    337.000000
25%       2.900000    10.000000    15.346667   1087.000000
50%       6.000000    16.000000    21.333333   1539.000000
75%      10.500000    27.000000    28.915033   2365.500000
max     310.300000   336.000000          inf  25569.000000

Значения стандартного отклонения и среднего считаются некорректно, поскольку есть строки с нулевой продолжительностью поездки. Такие данные являются мусорными, от них нужно избавиться.

#### 1.3 Предобработка данных

Процесс предобработки данных подробно описан в предыдущей лабораторной работе. 
В него входят следующие этапы:
- заполнение/удаление пропусков
- работа с явными/неявными дубликатами
- приведение значений к корректному типу данных

In [5]:
import numpy as np
df.loc[df['time']==0, 'time'] = np.nan

In [6]:
df.isna().sum()

start_date      0
end_date        0
category        0
start_loc       0
stop_loc        0
miles           0
purpose       501
time            4
speed           0
price           0
dtype: int64

Поле PURPOSE содержит 501 пропуск, ячейки будут заполнены "Unknown purpose". В поле time пропущено всего 4 значения, эти строки можно удалить.

In [8]:
df['purpose'] = df['purpose'].fillna('Unknown Purpose')
df=df.dropna(subset='time').reset_index(drop=True)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   start_date  1095 non-null   str
 1   end_date    1095 non-null   str
 2   category    1095 non-null   str
 3   start_loc   1095 non-null   str
 4   stop_loc    1095 non-null   str
 5   miles       1095 non-null   float64
 6   purpose     1095 non-null   str
 7   time        1095 non-null   float64
 8   speed       1095 non-null   float64
 9   price       1095 non-null   float64
dtypes: float64(4), str(6)
memory usage: 170.3 KB